# Generated by Django 3.1.5 on 2021-02-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='booked_seats',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Seat'),
        ),
    ]
