# Generated by Django 3.1.5 on 2021-02-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210222_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='booked_seats',
            field=models.ManyToManyField(blank=True, to='movies.Seat'),
        ),
    ]
